<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="EC2AMAZ-S11DBRH" failures="1" tests="2" name="runners.TestRunner" time="11.675" errors="0" timestamp="2023-08-25T05:45:54 GMT" skipped="0">
  <testcase classname="runners.TestRunner" name="runScenario" time="4.880">
    <failure message="expected [Welcome to the Secure Area. When you are done click logout below.] but found [This is where you can log into the secure area. Enter tomsmith for the username and SuperSecretPassword! for the password. If the information is wrong you should see error messages.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Welcome to the Secure Area. When you are done click logout below.] but found [This is where you can log into the secure area. Enter tomsmith for the username and SuperSecretPassword! for the password. If the information is wrong you should see error messages.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at stepdefinition.Login.homepage_is_displayed(Login.java:48)
at âœ½.Homepage is displayed(file:///C:/Users/Administrator/git/testcucumber/src/test/resources/features/login.feature:18)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="runners.TestRunner" name="runScenario" time="6.795"/>
  <system-out/>
</testsuite> <!-- runners.TestRunner -->
